### ISSUE TITLE
bad output with `mlt deploy --no-push`

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#109] opened 2018-03-26 23:21 UTC
```
Skipping image push
Deploying None
``` 
We are `deploying None`, but why tell the user this?

**Comment by dmsuehir** [comment] 2018-05-01 17:51
@s1113950 closing this because we are unable to reproduce.  Reopen if you are seeing this again.

**Closed by dmsuehir** 2018-05-01 17:51 UTC
Labels: importance/low
